const { Client, MessageMedia, LocalAuth } = require('whatsapp-web.js')
const qrcode = require('qrcode-terminal')


const client = new Client({
    authStrategy: new LocalAuth()
})

function initializeWhatsapp () {
    client.on('qr', qr => {
        qrcode.generate(qr, {small: true})
    });
    client.on('authenticated', (session) => console.log(`Autenticado`, session))
    client.on('ready', () => console.log('‍O ChatBot está pronto e escutando o WhatsApp '))
    client.initialize();
    return client;
}

async function sendMedia( sender, imgUrl, contact) {
    const media = await MessageMedia.fromUrl(imgUrl)
    const options = {
        mentions: [contact], 
        caption: `_Generated by @${contact.id.user}_`, 
        media: media,
        sendMediaAsSticker: true
    }
    await client.sendMessage(sender, media, options)
}

async function sendMessage(sender, message, ) {
    if (!message) return;
    await client.sendMessage(sender, message)
}


module.exports = {
    initializeWhatsapp,
    sendMedia,
    sendMessage,
}